import { createClient } from "jsr:@supabase/supabase-js@2";
import { getCorsHeaders } from "../_shared/cors.ts";
import {
  venueOwnerPasswordResetEmail,
  sendBrandedEmail,
} from "../_shared/brandedEmail.ts";

Deno.serve(async (req) => {
  const requestOrigin = req.headers.get("origin");
  const corsHeaders = getCorsHeaders(requestOrigin);

  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  try {
    const authHeader = req.headers.get("authorization");
    if (!authHeader) {
      return new Response(JSON.stringify({ error: "Unauthorized" }), {
        status: 401, headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
    const anonKey = Deno.env.get("SUPABASE_ANON_KEY")!;
    const serviceKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");
    
    if (!serviceKey) {
      return new Response(JSON.stringify({ error: "Server misconfiguration" }), {
        status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const supabase = createClient(supabaseUrl, anonKey, {
      global: { headers: { Authorization: authHeader } },
    });
    const svc = createClient(supabaseUrl, serviceKey);

    const { data: { user }, error: authErr } = await supabase.auth.getUser();
    if (authErr || !user) {
      return new Response(JSON.stringify({ error: "Unauthorized" }), {
        status: 401, headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const { data: adminProfile } = await supabase
      .from("profiles")
      .select("role")
      .eq("id", user.id)
      .single();

    if (adminProfile?.role !== "admin" && adminProfile?.role !== "super_admin") {
      return new Response(JSON.stringify({ error: "Admin only" }), {
        status: 403, headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const body = await req.json();
    const targetUserId = body?.userId as string | undefined;
    let password = String(body?.password ?? "").trim();

    if (!targetUserId) {
      return new Response(JSON.stringify({ error: "userId is required" }), {
        status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const isAutoGenerated = !password;
    if (!password) {
      password = crypto.randomUUID().replace(/-/g, "").slice(0, 12) + "Aa1!";
    }

    // Fetch user details for the email
    const { data: profile } = await svc
      .from("profiles")
      .select("email, full_name")
      .eq("id", targetUserId)
      .single();

    if (!profile || !profile.email) {
      return new Response(JSON.stringify({ error: "Target user not found or has no email" }), {
        status: 404, headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    // Prepare user metadata update
    // Only force password reset if auto-generated
    const { data: currentAuthUser, error: getUserErr } = await svc.auth.admin.getUserById(targetUserId);
    if (getUserErr || !currentAuthUser?.user) {
      return new Response(JSON.stringify({ error: "Auth user not found" }), {
        status: 404, headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const currentMetadata = currentAuthUser.user.user_metadata || {};
    const updatedMetadata = {
      ...currentMetadata,
      requires_password_change: isAutoGenerated ? true : false
    };

    const { error: updateErr } = await svc.auth.admin.updateUserById(targetUserId, {
      password,
      user_metadata: updatedMetadata
    });

    if (updateErr) {
      return new Response(JSON.stringify({ error: updateErr.message }), {
        status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    // Audit log
    await svc.from("audit_log").insert({
      admin_id: user.id,
      action: "reset_venue_owner_password",
      target_type: "profile",
      target_id: targetUserId,
      details: { email: profile.email, autoGenerated: isAutoGenerated },
    });

    // Send email
    try {
      const emailPayload = venueOwnerPasswordResetEmail(profile.email, profile.full_name ?? "", password, isAutoGenerated);
      const emailResult = await sendBrandedEmail(emailPayload);
      if (emailResult.error) {
        console.warn("[admin-reset-venue-owner-password] Reset email failed:", emailResult.error);
      } else {
        console.log("[admin-reset-venue-owner-password] Reset email sent to:", profile.email);
      }
    } catch (emailErr: any) {
      console.warn("[admin-reset-venue-owner-password] Reset email error:", emailErr?.message);
    }

    return new Response(
      JSON.stringify({
        success: true,
        temporaryPassword: isAutoGenerated ? password : null,
      }),
      { status: 200, headers: { ...corsHeaders, "Content-Type": "application/json" } },
    );
  } catch (err: any) {
    console.error("admin-reset-venue-owner-password:", err);
    return new Response(JSON.stringify({ error: err.message ?? "Internal error" }), {
      status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
